---
name: CI

on:
  push:
    branches: [main, dev]
    paths-ignore:
      - '**.md'
      - 'LICENSE*'
      - '.gitignore'
      - '.github/workflows/release.yml'
  pull_request:
    branches: [main, dev]
    paths-ignore:
      - '**.md'
      - 'LICENSE*'
      - '.gitignore'
      - '.github/workflows/release.yml'

jobs:
  ci:
    uses: riccione/github-workflows/.github/workflows/rust-ci.yml@v3
    with:
      apt_packages: >-
        pkg-config
        libgtk-4-dev
        build-essential
